# This is example language action workflow file

name: Generate web markdown

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch to use YAML files from'
        required: true
        type: string
      model_folder:
        description: 'Enter folder to use YAML files from'
        required: true
        type: string
jobs:
  shared-workflow-name:
    uses: owaspsamm/core/.github/workflows/reusable-yaml-process.yml@438ef84c34d08befb5cd413a3344d1e6e1f75e9e
    with:
      language: tt
      branch: ${{inputs.branch}}
      model_folder: ${{inputs.model_folder}}
